export const CHANGE_WINDSPEED = `CHANGE_WINDSPEED`
export const CHANGE_SAILING = `CHANGE_SAILING`
export const CHANGE_AIR_TEMP_PRESSURE = `CHANGE_AIR_TEMP_PRESSURE`
export const CHANGE_WATER_TEMP = `CHANGE_WATER_TEMP`
export const CHANGE_WATER_DEPTH = `CHANGE_WATER_DEPTH`
export const CHNAGE_SOG = `CHNAGE_SOG`
export const CHANGE_HV1 = `CHANGE_HV1`
export const CHANGE_HV2 = `CHANGE_HV2`
export const CHANGE_DC1 = `CHANGE_DC1`
export const CHANGE_DC2 = `CHANGE_DC2`
export const CHANGE_ELECTRIC_RPM_MOTORMT2 = `CHANGE_ELECTRIC_RPM_MOTORMT2`
export const CHANGE_RIGHT_UNDERENGINE_MOTOR = `CHANGE_RIGHT_UNDERENGINE_MOTOR`
export const CHANGE_LEFT_UNDERENGINE_MOTOR = `CHANGE_LEFT_UNDERENGINE_MOTOR`
export const CHANGE_UNDER_ENGINE_SOG = `CHANGE_UNDER_ENGINE_SOG`
export const CHANGE_UNDERENGINE_LEFT_WATER_TEMP = `CHANGE_UNDERENGINE_LEFT_WATER_TEMP`
export const CHANGE_UNDERENGINE_RIGHT_WATER_DEPTH = `CHANGE_UNDERENGINE_RIGHT_WATER_DEPTH`
export const CHANGE_UNDERENGINE_RIGHT_RPM = `CHANGE_UNDERENGINE_RIGHT_RPM`
export const CHANGE_UNDERENGINE_LEFT_RPM = `CHANGE_UNDERENGINE_LEFT_RPM`
export const CHANGE_SAILING_LEFT_SPEED = `CHANGE_SAILING_LEFT_SPEED`
export const CHANGE_SAILING_RIGHT_SOG = `CHANGE_SAILING_RIGHT_SOG`

//Change Langugae Modal
export const LANGUAGE_MODAL = `LANGUAGE_MODAL`

// Lower Deck Button
export const SYSTEM_MAIN_LEFT_WASHING_MACHINE = `SYSTEM_MAIN_LEFT_WASHING_MACHINE`
export const SYSTEM_MAIN_LEFT_GRAY_WATER_PUMP = `SYSTEM_MAIN_LEFT_GRAY_WATER_PUMP`
export const SYSTEM_MAIN_LEFT_TOLIT = `SYSTEM_MAIN_LEFT_TOLIT`
export const SYSTEM_MAIN_LEFT_VENTILATION = `SYSTEM_MAIN_LEFT_VENTILATION`
export const SYSTEM_MAIN_LEF_BILGE_PUMP_CENTER = `SYSTEM_MAIN_LEF_BILGE_PUMP_CENTER`
export const SYSTEM_MAIN_LEFT_BOILER = `SYSTEM_MAIN_LEFT_BOILER`
export const SYSTEM_MAIN_LEFT_WATER_PUMP = `SYSTEM_MAIN_LEFT_WATER_PUMP`
export const SYSTEM_MAIN_LEFT_BLIGE_AFT = `SYSTEM_MAIN_LEFT_BLIGE_AFT`
export const SYSTEM_MAIN_LEFT_AIR_CON = `SYSTEM_MAIN_LEFT_AIR_CON`

// Lower Deck switches 
export const LOWER_DECK_LIGHT_BB = `LOWER_DECK_LIGHT_BB`
export const LOWER_DECK_LIGHT_STB = `LOWER_DECK_LIGHT_STB`
export const LOWER_DECK_OUTLETS_BB = `LOWER_DECK_OUTLETS_BB`
export const LOWER_DECK_OUTLETS_STB = `LOWER_DECK_OUTLETS_STB`

// Upper Deck
export const UPPER_DECK_LIGHT_SALON = `UPPER_DECK_LIGHT_SALON`
export const UPPER_DECK_OUTLETS_SALON = `UPPER_DECK_OUTLETS_SALON`
export const UPPER_DECK_LIGHT_OUTSIDE = `UPPER_DECK_LIGHT_OUTSIDE`
export const UPPER_DECK_NAV_EQUIPMENT = `UPPER_DECK_NAV_EQUIPMENT`

export const CHANGE_MQTT_CLIENT = `CHANGE_MQTT_CLIENT`

// sailing center wheel
export const CHANGE_SAILING_HEADING = `CHANGE_SAILING_HEADING`
export const CHANGE_RUDDER_POSITION = `CHANGE_RUDDER_POSITION`
export const SAILING_CENTER_WATER_TEMP = `SAILING_CENTER_WATER_TEMP`
export const SAILING_CENTER_DEPT = `SAILING_CENTER_DEPT`

// UnderEngine Cetner View
export const CHANGE_UNDERENGINE_HEADING = `CHANGE_UNDERENGINE_HEADING`
export const CHANGE_UNDERENGINE_RUDDER_POSITION = `CHANGE_UNDERENGINE_RUDDER_POSITION`

// Status screen
export const CHANGE_FRESHWATER_BB = `CHANGE_FRESHWATER_BB`
export const CHANGE_FRESHWATER_STB = `CHANGE_FRESHWATER_STB`
export const CHANGE_BLACKWATER_STB = `CHANGE_BLACKWATER_STB`
export const CHANGE_BLACKWATER_BB = `CHANGE_BLACKWATER_BB`
export const CHANGE_DIESEL = `CHANGE_DIESEL`
export const CHANGE_GENERATOR_SWITCH = `CHANGE_GENERATOR_SWITCH`
export const CHANGE_SYSTEM_RPM = `CHANGE_SYSTEM_RPM`

// Welcome screen
export const CHANGE_WELCOME_AIRCON = `CHANGE_WELCOME_AIRCON`
export const CHANGE_WELCOME_POWER_UP = `CHANGE_WELCOME_POWER_UP`
export const CHANGE_WELCOME_SYSTEM_CHECK = `CHANGE_WELCOME_SYSTEM_CHECK`

export const CHANGE_GOODBYE_INHARBOUR = `CHANGE_GOODBYE_INHARBOUR`
export const CHANGE_GOODBYE_ATANCHOR = `CHANGE_GOODBYE_ATANCHOR`
export const CHANGE_GOODBYE_LONGTERM = `CHANGE_GOODBYE_LONGTERM`

// System button
export const LOWERDECK_RIGHT_ICE_CUBE_MAKER = `LOWERDECK_RIGHT_ICE_CUBE_MAKER`
export const LOWERDECK_RIGHT_FREEZER = `LOWERDECK_RIGHT_FREEZER`
export const LOWERDECK_RIGHT_VENTILATION = `LOWERDECK_RIGHT_VENTILATION`
export const LOWERDECK_RIGHT_WATER_PUMP_AIRCON = `LOWERDECK_RIGHT_WATER_PUMP_AIRCON`
export const LOWERDECK_RIGHT_GRAY_WATER_PUMP = `LOWERDECK_RIGHT_GRAY_WATER_PUMP`
export const LOWERDECK_RIGHT_TOLIT = `LOWERDECK_RIGHT_TOLIT`
export const LOWERDECK_RIGHT_BILGE_PUMP_CENTER = `LOWERDECK_RIGHT_BILGE_PUMP_CENTER`
export const LOWERDECK_RIGHT_BILGE_PUMP_AFT = `LOWERDECK_RIGHT_BILGE_PUMP_AFT`
export const LOWERDECK_RIGHT_AIRCON = `LOWERDECK_RIGHT_AIRCON`
export const LOWERDECK_RIGHT_WATERMAKER = `LOWERDECK_RIGHT_WATERMAKER`

// Upper Deck Left btn
export const UPPERDECK_LEFT_AIR_CON = `UPPERDECK_LEFT_AIR_CON`
export const UPPERDECK_LEFT_FREEZER = `UPPERDECK_LEFT_FREEZER`
export const UPPERDECK_LEFT_STOVE = `UPPERDECK_LEFT_STOVE`
export const UPPERDECK_LEFT_HOOD = `UPPERDECK_LEFT_HOOD`
export const UPPERDECK_LEFT_OVEN = `UPPERDECK_LEFT_OVEN`
export const UPPERDECK_LEFT_QUOOKER = `UPPERDECK_LEFT_QUOOKER`

// UpperDeck Right Btn
export const UPPERDECK_RIGHT_FURLER = `UPPERDECK_RIGHT_FURLER`
export const UPPERDECK_RIGHT_CAPSTAN = `UPPERDECK_RIGHT_CAPSTAN`
export const UPPERDECK_RIGHT_ANCHOR = `UPPERDECK_RIGHT_ANCHOR`
export const UPPERDECK_RIGHT_VHF = `UPPERDECK_RIGHT_VHF`
export const UPPDERDECK_RIGHT_REFRIDGERATOR = `UPPDERDECK_RIGHT_REFRIDGERATOR`
export const UPPERDECK_RIGHT_TV = `UPPERDECK_RIGHT_TV`
export const UPPERDECK_RIGHT_HIFI = `UPPERDECK_RIGHT_HIFI`
export const UPPERDECK_RIGHT_WINCHES = `UPPERDECK_RIGHT_WINCHES`
export const UPPERDECK_RIGHT_HELM = `UPPERDECK_RIGHT_HELM`

// Sailing screen button
export const SAILING_NAV_QUIPMENT = `SAILING_NAV_QUIPMENT`
export const SAILING_WINCHES = `SAILING_WINCHES`
export const SAILING_WINDLASS = `SAILING_WINDLASS`
export const SAILING_HYDRO_GEN_STD = `SAILING_HYDRO_GEN_STD`
export const SAILING_HYDRO_GEN_BB = `SAILING_HYDRO_GEN_BB`

// Direction GPS button
export const NORTH_DIRECTION = `NORTH_DIRECTION`
export const WEST_DIRECTION = `WEST_DIRECTION`

// UnderEngine screen button
export const CHANGE_UNDERENGINE_WINCHES = `CHANGE_UNDERENGINE_WINCHES`
export const CHANGE_UNDERENGINE_WINDLASS = `CHANGE_UNDERENGINE_WINDLASS`
export const CHANGE_UNDERENGINE_RIGHT_CAPSTAN_WINCHES = `CHANGE_UNDERENGINE_RIGHT_CAPSTAN_WINCHES`

export const CHANGE_UNDERENGINE_LEFT_NAV_QUIPMENT = `CHANGE_UNDERENGINE_LEFT_NAV_QUIPMENT`
export const CHANGE_UNDERENGINE_LEFT_PROPULSION = `CHANGE_UNDERENGINE_LEFT_PROPULSION`
export const CHANGE_UNDERENGINE_LEFT_GENERATOR = `CHANGE_UNDERENGINE_LEFT_GENERATOR`

// Decimal Format
export const CHANGE_DECIMAL_FORMAT = `CHANGE_DECIMAL_FORMAT`

export const CHNAGE_FRESHWATER_COLOR_SCALE = `CHNAGE_FRESHWATER_COLOR_SCALE`
export const CHNAGE_BLACKWATER_COLOR_SCALE = `CHNAGE_BLACKWATER_COLOR_SCALE`
export const CHNAGE_DIESEL_COLOR_SCALE = `CHNAGE_DIESEL_COLOR_SCALE`


// status under disconnect button
export const CHANGE_BMS24 = `CHANGE_BMS24`
export const CHANGE_BMS100 = `CHANGE_BMS100`
export const CHANGE_MODBUS = `CHANGE_MODBUS`
export const CHANGE_MOTOR = `CHANGE_MOTOR`
export const CHANGE_N2K = `CHANGE_N2K`


export const CHANGE_TURN_ON_DARK_THEME = `CHANGE_TURN_ON_DARK_THEME`
export const CHANGE_TURN_OFF_DARK_THEME = `CHANGE_TURN_OFF_DARK_THEME`
export const CHANGE_THEME = `CHANGE_THEME`
export const CHANGE_SAILING_ETA = `CHANGE_SAILING_ETA`
export const CHANGE_UNDERENGINE_ETA = `CHANGE_UNDERENGINE_ETA`
export const FALSE_HEART_BEAT = `FALSE_HEART_BEAT`
export const UNDER_ENGINE_DTW = `UNDER_ENGINE_DTW`
export const SAILING_DTW = `SAILING_DTW`
export const SAILING_LEFT_TWA = `SAILING_LEFT_TWA`
export const SAILING_CENTER_T = `SAILING_CENTER_T`
export const UNDER_ENGINE_CENTRAL_SPEED = `UNDER_ENGINE_CENTRAL_SPEED`
export const CHANGE_CURRENT_SCREEN = `CHANGE_CURRENT_SCREEN`